
language: python
python:
  - "3.7"
cache: pip
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install unittest2
script:
 - python scripts/unit_tests.py
 - python scripts/FKtest.py